/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 06-март-2022 14:27:24 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cargos_id_seq;
DROP SEQUENCE IF EXISTS cities_id_seq;
DROP SEQUENCE IF EXISTS driver_application_id_seq;
DROP SEQUENCE IF EXISTS locations_id_seq;
DROP SEQUENCE IF EXISTS orders_id_seq;
DROP SEQUENCE IF EXISTS roles_id_seq;
DROP SEQUENCE IF EXISTS statuses_id_seq;
DROP SEQUENCE IF EXISTS streets_id_seq;
DROP SEQUENCE IF EXISTS transport_application_id_seq;
DROP SEQUENCE IF EXISTS transport_types_id_seq;
DROP SEQUENCE IF EXISTS transports_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;
DROP SEQUENCE IF EXISTS vehicle_parameters_vehicle_id_seq;

/* Drop Tables */

DROP TABLE IF EXISTS cargos CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS driver_application CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orders_transports CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS streets CASCADE;
DROP TABLE IF EXISTS transport_application CASCADE;
DROP TABLE IF EXISTS transport_types CASCADE;
DROP TABLE IF EXISTS transports CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS vehicle_parameters CASCADE;

/* Create Tables */

CREATE TABLE cargos
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"cargos_id_seq"'::text)::regclass),
	weight smallint NOT NULL,
	length smallint NOT NULL,
	width smallint NOT NULL,
	height smallint NOT NULL,
	name varchar(50) NOT NULL,
	order_id bigint NOT NULL
);

CREATE TABLE cities
(
	id smallint NOT NULL   DEFAULT NEXTVAL(('"cities_id_seq"'::text)::regclass),
	name varchar(50) NOT NULL
);

CREATE TABLE driver_application
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"driver_application_id_seq"'::text)::regclass),
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	phone_number varchar(15) NOT NULL,
	email varchar(255) NOT NULL
);

CREATE TABLE locations
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"locations_id_seq"'::text)::regclass),
	city_id smallint NOT NULL,
	street_id smallint NOT NULL,
	home smallint NOT NULL
);

CREATE TABLE orders
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"orders_id_seq"'::text)::regclass),
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL,
	owner_id bigint NOT NULL,
	from_location bigint NOT NULL,
	to_location bigint NOT NULL,
	status_id smallint NOT NULL
);

CREATE TABLE orders_transports
(
	order_id bigint NOT NULL,
	transport_id bigint NOT NULL,
	actual_distance smallint NOT NULL
);

CREATE TABLE roles
(
	id smallint NOT NULL   DEFAULT NEXTVAL(('"roles_id_seq"'::text)::regclass),
	name varchar(50) NOT NULL
);

CREATE TABLE statuses
(
	id smallint NOT NULL   DEFAULT NEXTVAL(('"statuses_id_seq"'::text)::regclass),
	status_name varchar(50) NOT NULL
);

CREATE TABLE streets
(
	id smallint NOT NULL   DEFAULT NEXTVAL(('"streets_id_seq"'::text)::regclass),
	name varchar(50) NOT NULL
);

CREATE TABLE transport_application
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"transport_application_id_seq"'::text)::regclass),
	driver_id bigint NOT NULL,
	document_uuid uuid NOT NULL
);

CREATE TABLE transport_types
(
	id smallint NOT NULL   DEFAULT NEXTVAL(('"transport_types_id_seq"'::text)::regclass),
	type_name varchar(50) NOT NULL
);

CREATE TABLE transports
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"transports_id_seq"'::text)::regclass),
	year_of_production date NOT NULL,
	brand varchar(50) NOT NULL,
	model varchar(50) NOT NULL,
	registration_number varchar(7) NOT NULL,
	driver_id bigint NOT NULL,
	type_id smallint NOT NULL,
	vin varchar(17) NOT NULL,
	insurance_expiry_ts timestamp without time zone NOT NULL
);

CREATE TABLE users
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('"users_id_seq"'::text)::regclass),
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	email varchar(255) NOT NULL,
	password_hash varchar(24) NOT NULL,
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL,
	rating numeric(3,2) NOT NULL,
	role_id smallint NOT NULL
);

CREATE TABLE vehicle_parameters
(
	vehicle_id bigint NOT NULL   DEFAULT NEXTVAL(('"vehicle_parameters_vehicle_id_seq"'::text)::regclass),
	width smallint NOT NULL,
	height smallint NOT NULL,
	length smallint NOT NULL,
	capacity smallint NOT NULL,
	mileage smallint NOT NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cargos ADD CONSTRAINT "PK_cargos"
	PRIMARY KEY (id);

ALTER TABLE cities ADD CONSTRAINT "PK_cities"
	PRIMARY KEY (id);

ALTER TABLE driver_application ADD CONSTRAINT "PK_dirver_application"
	PRIMARY KEY (id);

ALTER TABLE locations ADD CONSTRAINT "PK_locations"
	PRIMARY KEY (id);

ALTER TABLE orders ADD CONSTRAINT "PK_orders"
	PRIMARY KEY (id);

ALTER TABLE orders_transports ADD CONSTRAINT "PK_orders_transports"
	PRIMARY KEY (order_id,transport_id);

ALTER TABLE roles ADD CONSTRAINT "PK_roles"
	PRIMARY KEY (id);

ALTER TABLE statuses ADD CONSTRAINT "PK_statuses"
	PRIMARY KEY (id);

ALTER TABLE streets ADD CONSTRAINT "PK_streets"
	PRIMARY KEY (id);

ALTER TABLE transport_application ADD CONSTRAINT "PK_transport_application"
	PRIMARY KEY (id);

ALTER TABLE transport_types ADD CONSTRAINT "PK_transport_types"
	PRIMARY KEY (id);

ALTER TABLE transports ADD CONSTRAINT "PK_transports"
	PRIMARY KEY (id);

ALTER TABLE users ADD CONSTRAINT "PK_users"
	PRIMARY KEY (id);

ALTER TABLE vehicle_parameters ADD CONSTRAINT "PK_vehicle_parameters"
	PRIMARY KEY (vehicle_id);

/* Create Foreign Key Constraints */

ALTER TABLE cargos ADD CONSTRAINT "FK_cargos_orders"
	FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE locations ADD CONSTRAINT "FK_locations_cities"
	FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE locations ADD CONSTRAINT "FK_locations_streets"
	FOREIGN KEY (street_id) REFERENCES streets (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE orders ADD CONSTRAINT "FK_orders_locations_from"
	FOREIGN KEY (from_location) REFERENCES locations (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE orders ADD CONSTRAINT "FK_orders_locations_to"
	FOREIGN KEY (to_location) REFERENCES locations (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE orders ADD CONSTRAINT "FK_orders_statuses"
	FOREIGN KEY (status_id) REFERENCES statuses (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE orders ADD CONSTRAINT "FK_orders_users"
	FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE orders_transports ADD CONSTRAINT "FK_orders_transports_orders"
	FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE orders_transports ADD CONSTRAINT "FK_orders_transports_transports"
	FOREIGN KEY (transport_id) REFERENCES transports (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE transport_application ADD CONSTRAINT "FK_transport_application_users"
	FOREIGN KEY (driver_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE transports ADD CONSTRAINT "FK_transports_transport_types"
	FOREIGN KEY (type_id) REFERENCES transport_types (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE transports ADD CONSTRAINT "FK_transports_users"
	FOREIGN KEY (driver_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE users ADD CONSTRAINT "FK_users_roles"
	FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE vehicle_parameters ADD CONSTRAINT "FK_vehicle_parameters_transports"
	FOREIGN KEY (vehicle_id) REFERENCES transports (id) ON DELETE No Action ON UPDATE No Action;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE cargos_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE cities_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE driver_application_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE locations_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE orders_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE roles_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE statuses_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE streets_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE transport_application_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE transport_types_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE transports_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE users_id_seq INCREMENT 1 START 1;
CREATE SEQUENCE vehicle_parameters_vehicle_id_seq INCREMENT 1 START 1;